### ISSUE TITLE
Consider providing an option to omit the ambient declaration wrapper

### ISSUE THREAD

**Issue by aluanhaddad** [typings/core#177]
Greetings.

If this has been raised before, I apologize.

I realize that the a significant aspect of the design of Typings is based around install-name-customizable ambient declarations. Providing this behavior is valuable.

However, for those of us who wish to use `"paths"` instead, explicitly mapping each module in a tsconfig file, and not introducing any ambient module names, it would be great if Typings would allow an install time option that would simply not inject the `declare module "m"` wrapper.

Typings has many great features, such as being able to install declarations directly from sources other than DefinitelyTyped, that I find highly valuable. I am also not completely soled on `@types` as there are issues, such as the `/// <reference types="path" />` construct, which I think are ill considered as well as a number of use cases that it does not cover.

Unfortunately I tend to avoid using Typings simply because of the automatically generated wrapper.

Thank you and keep up the awesome work!

**Comment by blakeembrey** [comment]
Unfortunately it's impossible to do. I actually spent the first three months of Typings development trying to achieve something like this, it would require you to follow all the types and squash it down into a single module file. There's still an open issue on the TypeScript repo for something like this. I decided it was just too difficult and took the simple shortcut of generating global module declarations with namespacing instead. I'm happy to keep the discussion open, and/or close the issue, just need to note it's something I'm unlikely to look into at this time anymore. The tool itself is stable and with TypeScript native resolution I'd like to point people to that instead. Thanks!

**Comment by aluanhaddad** [comment]
Thank you for your response and for the time and effort you have already invested in the pursuit of such functionality.

While I think this discussion should be ongoing at least in the abstract (as a community we need better declaration acquisition and  versioning strategies), I think that it would be best held in the broader TypeScript community, such as in the still open issue you mention, so feel free to close this.

**Comment by blakeembrey** [comment]
No worries 😄 I see you already responded, but I'll link the issue in question for future reference: https://github.com/Microsoft/TypeScript/issues/4433. Can I ask what your primary goal is? The issue, for me, is even if you achieve this thing you need to resolve transitive module resolution - currently impossible because `paths` is hard-coded in `tsconfig.json` and can't be used for dependencies as a result. That would need to be resolved properly, which I don't think is too hard (probably just some metadata in the `.d.ts` or somewhere else to say where the definition was resolved to), but I don't think it's a priority for the TypeScript team.

**Comment by aluanhaddad** [comment]
Indeed transitivity is really where this becomes unworkable. I was initially going to reply with why my use case, which was fairly simple, but after thinking over your remarks and revisiting the source code in typing/core/src/compile.ts, I realized that while it would help with my use case, it would fall down for far too many other use cases to make for a good general feature.

My use case involved Aurelia. I wanted the exact declaration versions corresponding to each installed package, especially since they generate these files as part of their build. 

Actually actually this worked quite well for that framework but their package structure is relatively flat, has few external dependencies, and all their dependencies are peers, with the exception of the WHATWGFetch typings which are now shipped with TypeScript itself.

Basically I hacked up a fairly hard-coded, brittle tool for installing packages for just that framework.

https://github.com/aluanhaddad/aurelia-types-installer

I wrote this for for my personal use, and that of a few clients, but primarily as a proof of concept.

It parses jspm config files and reads the `tsconfig.json` file (to determine resolution, module, and existing paths) and finds the exact tag versions of the JS currently installed. It downloads them from GitHub based on the tag and writes them into versioned subdirectories*.

It then generates or updates a file called `tsconfig.paths.json` with paths entries mapping to these directories. This file then needs to be manually referenced in the "inherits" clause of the `tsconfig.json`. The reason for for this is that my goal was to not add or modify the contents of any existing manifest or config files.

Basically, it was frustrating to have to generate a brittle, GitHub URL based declaration download client just to obtain the raw unwrapped files (this naturally also prevented using other sources). My first thought was to not do this at all and instead use Typings to acquire these files, but the wrapped nature of the resulting file was precisely what I was trying to avoid. Ultimately I wanted to also support other libraries, and handle any non Aurelia dependencies of Aurelia itself. Doing so is tremendously complex for the reasons you mention above. Again my thought was to leverage Typings to acquire these files.

If you've read through this long post, I appreciate it.

* actually it overlays them onto the folders created by jspm which actually works better than you would expect and provides a consumption experience analogous to the Aurelia beta releases, before they stopped shipping the declaration fIles along side each dist bundle. Overlaying the files was not a requirement but it was easy enough to do since the paths were being generated.

**Comment by blakeembrey** [comment]
One thing I did realise, and I'm not really sure if it does help you because I still didn't quite understand what you're doing (I can look into it more later, sorry!), is the transitivity issue could be made irrelevant with a definition squashing like in that issue. Assuming that squashing the definition really is the same feature regardless of how many files you end up with in the end, this can actually be an extremely useful and mainstream feature.

What I'd propose is that the definition squashing first does, is that it inlines every "external dependency" into the code itself. Sure, there can be a second mode that also inlines every import entirely so you end up with one file, but a great first step would be to compile every of your own `.d.ts` files with the externals inlined and then you don't need to worry about transitivity. It can also remove the issue of having to have dependencies on `@types/*` in modules published to NPM.

However, a major issue to all of this is the `private` and `protected` keywords. In their current form, it's based on the file location (e.g. the same file in two locations results in them being unassignable). This means inlining isn't possible with `private` or `protected` methods unless the TypeScript team looks into changing this.

**Comment by unional** [comment]
I'm not sure if I fully understand the issue, but without the wrapper today **TS2.0 included** we have declaration conflict when we try to have it flatten.

AFAIK,

```sh
- A@1.0
  - B@1.1
- B@2.0
```
will mess up if the typings of B@1.1 and B@2.0 is not compatible.

**Comment by aluanhaddad** [comment]
Sorry, I probably failed to explain my use case.

I didn't intend to squash or inline any declarations, although I can see how that can be quite useful.

I simply wanted a way to acquire the individual declaration files without their wrappers and manually wire them up via paths configuration.

Granted such an approach has many limitations, and is in fact questionable, but that was what I was trying to do.
