### ISSUE TITLE
Inferred naming / enable renaming for `declare module "x" {`?

### ISSUE THREAD

**Issue by unional** [typings/core#52]
**Pure brainstorming. Might not worth the effort, buggy, or align with vision**
While I understand the typings in DT is messy, would it be possible to do:
- `typings install dr=dt:domready`
  - lookup `declare module "domready" {` and rename to `declare module "dr" {`

**Comment by blakeembrey** [comment]
I don't think there's any value in doing this. It's not compatible with anything else, and we should stop trying to achieve ambient typings hacks - it takes away from actual ambient typing use-cases. If this were to happen, how will you handle `node.d.ts`, `webpack.d.ts`, `browserify.d.ts`, `electron.d.ts`, ... properly?

**Comment by unional** [comment]
No problem.  Was wondering would it help when `tsc` bundles everything to an `outFile`. (when `module: {systemjs,amd}`)

**Comment by blakeembrey** [comment]
If TypeScript removes the restriction and allows that, we should too. I just need to see it work first. Especially since the last time I looked at TypeScript `.d.ts` bundling it seemed more like path mapping anyway - which would require prefixing and not replacement. Mostly just need to see what it looks like to support it, but I don't want to hack existing legitimate use-cases.
